### ISSUE TITLE
matlab_kernel install is unpinned

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/repo2docker_wholetale#43]
New `matlab_kernel` release requires newer version of traitlets than is installed via r2d.
```
ImportError: cannot import name 'filefind' from 'traitlets.utils' (/srv/conda/envs/notebook/lib/python3.8/site-packages/traitlets/utils/__init__.py)
[I 09:01:23.031 NotebookApp] KernelRestarter: restarting kernel (4/5), new random ports
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/srv/conda/envs/notebook/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/matlab_kernel/__main__.py", line 2, in <module>
    from .kernel import MatlabKernel
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/matlab_kernel/kernel.py", line 22, in <module>
    from metakernel import MetaKernel, ExceptionWrapper
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/metakernel/__init__.py", line 1, in <module>
    from ._metakernel import (
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/metakernel/_metakernel.py", line 22, in <module>
    from ipykernel.kernelapp import IPKernelApp
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/ipykernel/kernelapp.py", line 42, in <module>
    from traitlets.utils import filefind
ImportError: cannot import name 'filefind' from 'traitlets.utils' (/srv/conda/envs/notebook/lib/python3.8/site-packages/traitlets/utils/__init__.py)
```

**Test case**
* On production, create and run a new Matlab Jupyter Kernel tale using https://github.com/whole-tale/matlab-example
* Inspect the image build logs for the below error about incompatible dependencies
* Inspect the container logs, you should see the above error
* Open and run the `multiplicative_arima_example.ipynb`, the Matlab kernel will not start and notebook fails to run
* Expected results: no build or container errors, notebook runs as expected.

**Comment by craig-willis** [comment]
The actual problem appears to be incompatible dependencies. Pinning matlab_kernel alone isn't sufficient.
```
#41 [stage-0 33/42] RUN /srv/conda/envs/notebook/bin/pip install matlab_kernel==0.16.11 jupyter-matlab-proxy==v0.3.2
#41 sha256:faf4e5b96d3615babf59a4930603adf8cfd4fccdee714d00f0782320ecc636e9
#41 3.304 Collecting matlab_kernel==0.16.11
#41 3.371   Downloading matlab_kernel-0.16.11-py3-none-any.whl (9.1 kB)
...
#41 4.032 Collecting metakernel>=0.23.0
#41 4.045   Downloading metakernel-0.29.0-py2.py3-none-any.whl (216 kB)
...
#41 4.603 Collecting ipykernel>=5.5.6
#41 4.615   Downloading ipykernel-6.13.0-py3-none-any.whl (131 kB)
...
#41 6.113 ERROR: ipykernel 6.13.0 has requirement ipython>=7.23.1, but you'll have ipython 7.16.1 which is incompatible.
#41 6.113 ERROR: ipykernel 6.13.0 has requirement jupyter-client>=6.1.12, but you'll have jupyter-client 6.1.6 which is incompatible.
#41 6.113 ERROR: ipykernel 6.13.0 has requirement tornado>=6.1, but you'll have tornado 6.0.4 which is incompatible.
#41 6.113 ERROR: ipykernel 6.13.0 has requirement traitlets>=5.1.0, but you'll have traitlets 4.3.3 which is incompatible.
#41 6.113 ERROR: metakernel 0.29.0 has requirement jedi>=0.18, but you'll have jedi 0.17.2 which is incompatible.
#41 6.113 ERROR: metakernel 0.29.0 has requirement jupyter-core>=4.9.2, but you'll have jupyter-core 4.6.3 which is incompatible.
...
#41 7.663   Attempting uninstall: ipykernel
#41 7.665     Found existing installation: ipykernel 5.3.4
#41 7.725     Uninstalling ipykernel-5.3.4:
#41 9.603       Successfully uninstalled ipykernel-5.3.4
#41 DONE 12.1s
```
